streamdal/console

- src/components/rules/rulesetAddEdit.tsx
- src/components/status/success.tsx
Make match config arg optional by default. Also, when success message is shown, scroll to it.
> validation bug and success scroll

- package-lock.json
- src/components/rules/menu.tsx
- src/components/rules/metrics/total.tsx
- src/components/rules/ruleSets.tsx
- src/components/rules/rulesetAddEdit.tsx
- src/components/rules/rulesetView.tsx
- src/lib/fetch.ts
- src/lib/metrics.ts
- src/lib/utils.ts
- src/pages/ruleset/edit.astro
- src/pages/ruleset/index.astro
* map, reduce and total metrics per ruleset and rule
* add top leve ruleset metrics to landing page
* add rulset detail view with total metrics and rule level metrics breakouts
* add polling to ruleset list and view
> * call metrics endpoint and parse prometheus log format

- src/components/rules/rule/addEdit.tsx
- src/components/rules/rule/failureMode.tsx
- src/components/rules/rulesetAddEdit.tsx
- src/components/rules/rulesetView.tsx
Managing rules in state ourselves was screwing up react hooks form.
> fix rule deletion

- src/components/rules/rule/addEdit.tsx
- src/components/rules/rulesetAddEdit.tsx
- Adds rule name field to rule
- Updates types, updates validation
> add rule name to form, add validation, update types

- components/nav/navMenu.tsx
- components/pipeline/pipelineMenu.tsx
- components/pipeline/stepMenu.tsx
- fresh.gen.ts
- islands/pipeline.tsx
- islands/pipelines.tsx
- lib/dummies.ts
- twind.config.ts
> flesh out pipeline step designs

- components/form/formSelect.tsx
- components/form/inlineInput.tsx
- components/form/validate.ts
- example.env
- islands/pipeline.tsx
Form fields have gotten a little heavy. Will clean up at some point.
> consolidate a bunch of nested for setting stuff, flesh out detective step stuff.

- components/form/checkboxGroup.tsx
- components/form/formSelect.tsx
- components/layout.tsx
- components/pipeline/stepArgs.tsx
- components/pipeline/stepCondition.tsx
- components/tooltip/tooltip.tsx
- islands/pipeline.tsx
- islands/pipelines.tsx
- lib/dummies.ts
- twind.config.ts
> add detective type, dynamic args and success/failure conditions

- components/modals/routedDeleteModal.tsx
- components/pipeline/pipelineMenu.tsx
- components/pipeline/stepMenu.tsx
- islands/pipeline.tsx
- routes/pipelines/[id]/delete.tsx
* hack a fix for flowbite not working with dynamically added components
> step delete

- components/layout.tsx
- components/serviceMap/customNodes.tsx
- components/serviceMap/nodeMenu.tsx
- fresh.gen.ts
- islands/opModal.tsx
- lib/fetch.ts
- lib/utils.ts
* adds client counts to operation node bubble with tool tip
* fix layout scroll issue
* refactor node data so we can more easily update it (coming soon) and to remove an extra iteration
> client counts

- components/serviceMap/customNodes.tsx
- islands/serviceMap.tsx
> ui updates from last demo

- components/form/formSelect.tsx
- components/form/validate.ts
- islands/pipeline.tsx
The step stuff needs to be refactored out into it's own component, it's a bit brittle right now. But, this fix makes it work for Monday's demo.
> quick and dirty fix for changing step types

- lib/fetch.ts
- lib/nodeMapper.ts
> map and wire up live client info

- components/serviceMap/customNodes.tsx
- lib/stream.ts
Also make the group node background non-transparent.
> add some basic error handling to our grpc server stream

- islands/opModal.tsx
- islands/serviceMap.tsx
I only do the fit on initial load and when new nodes are streamed in...and I only do it if nodes are off the screen.
> fit content to screen on load and incoming changes

- README.md
- components/serviceMap/customNodes.tsx
- lib/nodeMapper.ts
- routes/_layout.tsx
- version.ts
> add version to ui and some more layout fixes

- components/serviceMap/nodeMenu.tsx
- islands/peek.tsx
- lib/peek.ts
- lib/utils.ts
Peek view limit wasn't working properly, now it is.
> tail by audience

- components/serviceMap/customEdge.tsx
- components/serviceMap/expandedNodes.tsx
- components/serviceMap/nodeMenu.tsx
- deno.json
- fresh.gen.ts
- islands/customNodes.tsx
- islands/peek.tsx
- islands/serviceMap.tsx
- lib/edgeMetrics.ts
- lib/nodeMapper.ts
- lib/utils.ts
- routes/_app.tsx
- routes/_layout.tsx
I added custom edges and custom edge label renderers and spread things out on the y axis to make room for the labels.
> stream throughput and put them on our edges

- islands/customNodes.tsx
- Fixes bug that highlights operation even when operation hasn't been clicked on
> fix highlighting bug

- components/modals/oddAttachModal.tsx
- islands/opModal.tsx
- Fixes empty state in sidebar
> fix empty state in sidebar

- components/modals/schemaModal.tsx
- components/operation/schema.tsx
- islands/operationOpModal.tsx
-Sets scroll for schema in sidebar and make sure schema can scroll in modal
https://github.com/streamdal/console/assets/108096652/df685851-2663-42c9-9eb4-9496352f4d45
> make schema scrollable in sidebar and modal

- lib/nodeMapper.ts
This will need a comprehensive solution at some point, but for now these tweaks handle most of our straightforward examples.
> some layout fixes

- components/operation/operationActionMenu.tsx
> remove pause pipeline

- islands/drawer/tail.tsx
- lib/configs.ts
- routes/_app.tsx
@fritzstauff you'll need to add `STREAMDAL_CONSOLE_GOOGLE_ANALYTICS_KEY=<key>` to the demo ...I'll send you the key.
> tail socket bug and google analytics (demo only)

- islands/drawer/tail.tsx
- lib/tail.ts
- static/style.css
Also, stop tail entirely on pause.
> update tail colors

- components/pipeline/stepArgs.tsx
- islands/pipeline.tsx
Require a path for step types that should have one. Add custom dropdown of types for is_type type.
> fix up pipeline step arg validations

- components/notifications/notificationMenu.tsx
- fresh.gen.ts
- islands/nav.tsx
- islands/notification.tsx
- islands/notifications.tsx
- islands/pipelines.tsx
- lib/fetch.ts
- lib/mutation.ts
- routes/_layout.tsx
- routes/notifications/[id]/delete.tsx
- routes/notifications/[id]/index.tsx
- routes/notifications/add.tsx
- routes/notifications/index.tsx
- routes/notifications/save.tsx
- routes/partials/notifications/index.tsx
- routes/partials/pipelines/index.tsx
- routes/pipelines/index.tsx
> add notifications route, list view, update and delete
